INIT_SCREEN_GAME_MESSAGE_X_COORDINATE = 80
INIT_SCREEN_GAME_MESSAGE_Y_COORDINATE = 300

MAIN_LOOP_NEXT_MESSAGE_X_COORDINATE = 345
MAIN_LOOP_NEXT_MESSAGE_Y_COORDINATE = 0

MAIN_LOOP_SCORE_MESSAGE_X_COORDINATE = 330
MAIN_LOOP_SCORE_MESSAGE_Y_COORDINATE = 360

GAME_OVER_SCREEN_MESSAGE_X_COORDINATE = 35
GAME_OVER_SCREEN_MESSAGE_Y_COORDINATE = 300
