INIT_SQUARE_SIZE = 30
NUMBER_OF_SQUARES_IN_ROW = 10
NUMBER_OF_ROWS = 24
INIT_HIGHT = NUMBER_OF_ROWS * INIT_SQUARE_SIZE # changeIt
INIT_WIGHT = NUMBER_OF_SQUARES_IN_ROW * INIT_SQUARE_SIZE # changeIt

INIT_QUEUE_X = INIT_WIGHT + (INIT_SQUARE_SIZE*2)
INIT_QUEUE_Y = INIT_SQUARE_SIZE * 2
INIT_QUEUE_GAP = INIT_SQUARE_SIZE * 3
