INIT_SQUARE_SIZE = 30
NUMBER_OF_SQUARES_IN_ROW = 10
NUMBER_OF_ROWS = 24
INIT_HIGHT = NUMBER_OF_ROWS * INIT_SQUARE_SIZE # changeIt
INIT_WIGHT = NUMBER_OF_SQUARES_IN_ROW * INIT_SQUARE_SIZE # changeIt

INIT_QUEUE_X = INIT_WIGHT + (INIT_SQUARE_SIZE*2)
INIT_QUEUE_Y = INIT_SQUARE_SIZE * 2
INIT_QUEUE_GAP = INIT_SQUARE_SIZE * 3

POINTS_FOR_SQUARE = 1
POINTS_FOR_ROW = POINTS_FOR_SQUARE * NUMBER_OF_SQUARES_IN_ROW


SPEED_FALLING = 1000
SPEED_FALLING_SPEED_UP_INTERVAL = 10000
SPEED_FALLING_INCREASE = 50
SPEED_FALLING_MAX_SPEED = 200

SPEED_FALLING_BONUS = 1

BONUS_FOR_ROW_IN_ONE_MOVE = 2