FONT_NAME = "verdana"

INIT_SCREEN_GAME_MESSAGE_FONT_SIZE = 20
INIT_SCREEN_PLAYER_NAME_FONT_SIZE = 45

MAIN_LOOP_NEXT_FONT_SIZE = 60
MAIN_LOOP_SCORE_FONT_SIZE = 25

GAME_OVER_MESSAGE_FONT_SIZE = 20
GAME_OVER_SCREEN_SCORE_FONT_SIZE = 45