SQUARE_SIZE = 30
NUMBER_OF_SQUARES_IN_ROW = 10
NUMBER_OF_ROWS = 24

GAME_SCREEN_WIGHT = 17 * SQUARE_SIZE
GAME_SCREEN_HIGHT = NUMBER_OF_ROWS * SQUARE_SIZE
BOARD_WIGHT = NUMBER_OF_SQUARES_IN_ROW * SQUARE_SIZE
